name: dist

on:
  push:
    branches: [ release/* ]

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: env | sort

    - name: Get image
      run: |
        time docker pull ciio/libci-dev
        docker images | grep libci

    - run: |
        make -C pkg/docker libci-dist-ci
        ls -l pkg/docker/output

    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: pkg/docker/output/ci-0*

